// just to prevent load time so i fetched and added data in one place

export const newSongs = [
    {
        "320kbps": "true",
        "album": "Mere Ghar Ram Aaye Hain",
        "album_url": "https://www.jiosaavn.com/album/mere-ghar-ram-aaye-hain/dsife5uVB1k_",
        "albumid": "39209161",
        "artistMap": {
            "Jubin Nautiyal": "881158",
            "Manoj Muntashir": "473441",
            "Payal Dev": "653208"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2022 Super Cassettes Industries Private Limited",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "234",
        "encrypted_media_path": "NMKyboFo/FjJuhrj+FJtuKPCw8Kor3ayiokJWCn4qWgdcA2+WIxz7IRhZHrOUj/b",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyEs7nXKoT669b3hO1CR26pZ40TvOn/CswcBC83eH8qHylYR86Ia32Lhw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "q3ElTqvW",
        "image": "https://c.saavncdn.com/946/Mere-Ghar-Ram-Aaye-Hain-Hindi-2022-20221019191009-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "bajaao dhol swaagat mein, mere ghar ram aaye hain",
        "media_preview_url": "https://preview.saavncdn.com/946/9639eff1be049ac7f92683fc44dc9131_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/946/9639eff1be049ac7f92683fc44dc9131_320.mp4",
        "music": "Payal Dev",
        "music_id": "653208",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/mere-ghar-ram-aaye-hain/AVsuXSBBQWQ",
        "play_count": 41142951,
        "primary_artists": "Jubin Nautiyal, Payal Dev, Manoj Muntashir",
        "primary_artists_id": "881158, 653208, 473441",
        "release_date": "2022-10-20",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Jubin Nautiyal, Payal Dev, Manoj Muntashir",
        "song": "Mere Ghar Ram Aaye Hain",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910091894701",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091851192.mp3",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "ANIMAL",
        "album_url": "https://www.jiosaavn.com/album/animal/8Ps4qqBA6,Y_",
        "albumid": "49986024",
        "artistMap": {
            "Raj Shekhar": "671644",
            "Vishal Mishra": "702452"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2023 Super Cassettes Industries Private Limited",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "250",
        "encrypted_media_path": "NMKyboFo/FhT4ZofmBRqbaEiVD7OpCbJoqtNYZYmUWMqMK+mjPbuwA4xL02OfPN9",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyxinPKFDOONH/Et1cshd2AW1YovHZ/6DmCPFQJZHjAJNdM2cswzHLvRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "1e0En7YX",
        "image": "https://c.saavncdn.com/092/ANIMAL-Hindi-2023-20231124191036-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "Pehle bhi main tumse mila hun",
        "media_preview_url": "https://preview.saavncdn.com/092/b3acb226721d5e51e788e9838f0261c3_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/092/b3acb226721d5e51e788e9838f0261c3_320.mp4",
        "music": "Vishal Mishra",
        "music_id": "702452",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/pehle-bhi-main/QQ1bdBoHbms",
        "play_count": 24366371,
        "primary_artists": "Vishal Mishra, Raj Shekhar",
        "primary_artists_id": "702452, 671644",
        "release_date": "2023-11-24",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Vishal Mishra, Raj Shekhar",
        "song": "Pehle Bhi Main",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910092152247",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910092108907.mp3",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Ram Siya Ram",
        "album_url": "https://www.jiosaavn.com/album/ram-siya-ram/cy9LsEw-pn0_",
        "albumid": "25500145",
        "artistMap": {
            "Poonam Thakkar": "9521286",
            "Sachet Tandon": "3623110",
            "Shabbir Ahmed": "461011"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2021 Super Cassettes Industries Private Limited",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "265",
        "encrypted_media_path": "NMKyboFo/FiIyXExH+djtFzqZFSk1wBh2YXA5/PJS7w7OCVU6rSx95b8LkXvvS0q",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyYJ+5/mMmphgKGwkNDtSkT/MwZwumWrWHz1fM9uHMbp+aUIGETZOvHRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "HLulXlir",
        "image": "https://c.saavncdn.com/215/Ram-Siya-Ram-Hindi-2021-20210222031001-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "Lyrics",
        "media_preview_url": "https://preview.saavncdn.com/215/5a6134d5860b9b47cc9fb2e058e22a18_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/215/5a6134d5860b9b47cc9fb2e058e22a18_320.mp4",
        "music": "Poonam Thakkar",
        "music_id": "9521286",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/ram-siya-ram/OCQeXSxcXkE",
        "play_count": 85677917,
        "primary_artists": "Sachet Tandon",
        "primary_artists_id": "3623110",
        "release_date": "2021-02-22",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Sachet Tandon",
        "song": "Ram Siya Ram",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910091238843",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091195734.mp3",
        "webp": true,
        "year": "2021"
    },
    {
        "320kbps": "true",
        "album": "Guntur Kaaram",
        "album_url": "https://www.jiosaavn.com/album/guntur-kaaram/d28KxzEcK-Q_",
        "albumid": "49567583",
        "artistMap": {
            "Mahesh Babu": "461646",
            "Meenakshii Chaudhary": "9834460",
            "Ramajogayya Sastry": "455178",
            "Sahithi Chaganti": "1846675",
            "Sreeleela": "11731368",
            "Sri Krishna": "457304",
            "Thaman S": "544471"
        },
        "cache_state": "false",
        "copyright_text": "© 2023 Aditya Music",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "216",
        "encrypted_media_path": "NMKyboFo/FiWOPpG5+Bkd0osuFdHoaB6C5mrt4nd0pnkwiqMTrISizTp4PCfWZmB",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyAYSpkEihdkG4+AFn1gYNkJM9bhyDhDoC00is5zg9wSEUPgFYtzlXCxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "ARuXdxyk",
        "image": "https://c.saavncdn.com/000/Guntur-Kaaram-Telugu-2023-20240117152237-500x500.jpg",
        "is_dolby_content": false,
        "label": "Aditya Music",
        "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
        "language": "telugu",
        "lyrics_snippet": "Aa Kurchini Madatha Petti",
        "media_preview_url": "https://preview.saavncdn.com/000/a8b06cdf02fd61001823e10d55ad3ebe_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/000/a8b06cdf02fd61001823e10d55ad3ebe_320.mp4",
        "music": "Thaman S",
        "music_id": "544471",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/kurchi-madathapetti/MToeaRBITlg",
        "play_count": 4711785,
        "primary_artists": "Mahesh Babu, Thaman S, Sri Krishna, Sahithi Chaganti",
        "primary_artists_id": "461646, 544471, 457304, 1846675",
        "release_date": "2023-11-07",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Thaman S, Sri Krishna, Sahithi Chaganti, Mahesh Babu",
        "song": "Kurchi Madathapetti",
        "starred": "false",
        "starring": "Mahesh Babu, Sreeleela, Meenakshii Chaudhary",
        "triller_available": false,
        "type": "",
        "vcode": "010910402193409",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910402149524.mp3",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Ram Aayenge",
        "album_url": "https://www.jiosaavn.com/album/ram-aayenge/JXlb,rLRtAs_",
        "albumid": "49602829",
        "artistMap": {
            "Manoj Muntashir": "473441",
            "Payal Dev": "653208",
            "Vishal Mishra": "702452"
        },
        "cache_state": "false",
        "copyright_text": "℗ 2023 Super Cassettes Industries Private Limited",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "263",
        "encrypted_media_path": "NMKyboFo/FglfQ+r+ya+/5WFCjcHtCOlSmkfHkfpJ/9n3dffkw8HkV4ayKUskG5o",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyZAprV8/KeGyNRbHq6V8eqOly3lthqmSoC5aMuQB/cVeTYqx74J1fkRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "D3YbEDXN",
        "image": "https://c.saavncdn.com/336/Ram-Aayenge-Hindi-2023-20231108181532-500x500.jpg",
        "is_dolby_content": false,
        "label": "",
        "label_url": "/label/-albums/6DLuXO3VoTo_",
        "language": "hindi",
        "lyrics_snippet": "नैना भीगे-भीगे जाएँ, कैसे ख़ुशी ये छुपाएँ, राम आएँगे",
        "media_preview_url": "https://preview.saavncdn.com/336/9a856d1ea68a67128ec2885cdece697c_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/336/9a856d1ea68a67128ec2885cdece697c_320.mp4",
        "music": "Payal Dev",
        "music_id": "653208",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/ram-aayenge/NFsyUzF0b30",
        "play_count": 3192316,
        "primary_artists": "Payal Dev, Vishal Mishra, Manoj Muntashir",
        "primary_artists_id": "653208, 702452, 473441",
        "release_date": "2023-11-10",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Payal Dev, Vishal Mishra, Manoj Muntashir",
        "song": "Ram Aayenge",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910092180660",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910092138277.mp3",
        "webp": true,
        "year": "2023"
    }
]

export const relaxingSongs = [
    {
        "320kbps": "true",
        "album": "Relaxing Hari Strotam",
        "album_url": "https://www.jiosaavn.com/album/relaxing-hari-strotam/kwayQ6wTUOs_",
        "albumid": "37641144",
        "artistMap": {
            "Abhi B": "8497522",
            "Vidushi Yadav": "9549372"
        },
        "cache_state": "false",
        "copyright_text": "© 2022 Abhishek Baderiya",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "68",
        "encrypted_media_path": "NMKyboFo/Fg5DH7Of0wedzZFB4VoZguNHzzAOlbE2WOF1+02lgxQvh5DPRaE7LMo",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyppO1gnoqoPh6J82hZNoGsIQnUlkTNkBqUmpx/8OdMf0TO9Nar2vMdRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "0G4Y5D2E",
        "image": "https://c.saavncdn.com/180/Relaxing-Hari-Strotam-Sanskrit-2022-20220825175326-500x500.jpg",
        "is_dolby_content": false,
        "label": "Independent",
        "label_url": "/label/independent-albums/BtpnuQ5k-Mo_",
        "language": "sanskrit",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/180/806875ab49743d7481081274896f787e_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/180/806875ab49743d7481081274896f787e_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/relaxing-hari-strotam/QC9faEF0BXY",
        "play_count": 14655,
        "primary_artists": "Abhi B, Vidushi Yadav",
        "primary_artists_id": "8497522, 9549372",
        "release_date": "2022-08-31",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Abhi B, Vidushi Yadav",
        "song": "Relaxing Hari Strotam",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Bollywood Unwind - Romantic Classics in a Relaxing Urban Avatar",
        "album_url": "https://www.jiosaavn.com/album/bollywood-unwind-romantic-classics-in-a-relaxing-urban-avatar/MCsq4ztvlRY_",
        "albumid": "1452346",
        "artistMap": {
            "Akriti Kakar": "739763",
            "Arnab Chakraborty": "8410718",
            "R.D. Burman": "671145",
            "Sahir Ludhianvi": "455986"
        },
        "cache_state": "false",
        "copyright_text": "©  2015 Strumm Entertainment",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "228",
        "encrypted_media_path": "NMKyboFo/FitOwqQ3fACens2BblIBcZMu+3rFC0ITS1pLPyPBi27Rp+GX33jMJhi",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyPJj/aTHY4ShsXpJ2iqKB/0D0C5kT/0JfD3fpsJdu17m/YLzlVgFYYRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "ap3F0Ahb",
        "image": "https://c.saavncdn.com/001/Bollywood-Unwind-Romantic-Classics-in-a-Relaxing-Urban-Avatar-Hindi-2015-500x500.jpg",
        "is_dolby_content": false,
        "label": "Strumm Entertainment",
        "label_url": "/label/strumm-entertainment-albums/MxcESb9iLFU_",
        "language": "hindi",
        "lyrics_snippet": "jahaan tum ho, vahaan main bhi hoon",
        "media_preview_url": "https://preview.saavncdn.com/001/9df2b520d82727876e97fc2f2dc3b515_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/001/9df2b520d82727876e97fc2f2dc3b515_320.mp4",
        "music": "R.D. Burman",
        "music_id": "671145",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/wada-karo-unwind-version/ERhYd0RxX1E",
        "play_count": 2469652,
        "primary_artists": "Arnab Chakraborty, Akriti Kakar, R.D. Burman",
        "primary_artists_id": "8410718, 739763, 671145",
        "release_date": "2015-01-01",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Arnab Chakraborty, Akriti Kakar",
        "song": "Wada Karo - Unwind Version",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010911100798986",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010911100755468.mp3",
        "webp": false,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Mind Relaxing Lofi Mashups",
        "album_url": "https://www.jiosaavn.com/album/mind-relaxing-lofi-mashups/5,q,KV60uIk_",
        "albumid": "50645085",
        "artistMap": {
            "Kishan Bairwa Kanyakheri": "11516340"
        },
        "cache_state": "false",
        "copyright_text": "© 2023 Jbn Music Kanyakheri",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "1724",
        "encrypted_media_path": "NMKyboFo/FjBKG5oT/7C77/HQLjO0/ZDiLev3AETrKmwwOcCMzgziMq/8hnXGHbV",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyxjR/33jKbwK86xDTwgR4+4TrKW4UuciQlniZ9j9su7FUc79DP29zHxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "KrEODAJj",
        "image": "https://c.saavncdn.com/558/Mind-Relaxing-Lofi-Mashups-Hindi-2023-20231221201755-500x500.jpg",
        "is_dolby_content": false,
        "label": "Jbn Music Kanyakheri",
        "label_url": "/label/jbn-music-kanyakheri-albums/kmVs9PGLFpY_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/558/8ca5c203b20391fcc1c4a6b832cd6689_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/558/8ca5c203b20391fcc1c4a6b832cd6689_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/mind-relaxing-lofi-mashups/OxoufjBxfVk",
        "play_count": 923,
        "primary_artists": "Kishan Bairwa Kanyakheri",
        "primary_artists_id": "11516340",
        "release_date": "2023-12-31",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Kishan Bairwa Kanyakheri",
        "song": "Mind Relaxing Lofi Mashups",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2023"
    },
    {
        "320kbps": "true",
        "album": "Bollywood Unwind - Romantic Classics in a Relaxing Urban Avatar",
        "album_url": "https://www.jiosaavn.com/album/bollywood-unwind-romantic-classics-in-a-relaxing-urban-avatar/MCsq4ztvlRY_",
        "albumid": "1452346",
        "artistMap": {
            "Anjaan": "456712",
            "Mohammed Irfan": "743983",
            "Rajesh Roshan": "455518"
        },
        "cache_state": "false",
        "copyright_text": "©  2015 Strumm Entertainment",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "213",
        "encrypted_media_path": "NMKyboFo/FiX/TGRCHK6UMwtyooxC76zuvrBSO6jnrOG2f1QMEGCATJ9AafOhYq9",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDySGJjyX3+cpBKPnTmQ9lbJcjJtilQseIVeDANNWGkCZHnnPNWAu+TbBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "87EM7y6L",
        "image": "https://c.saavncdn.com/001/Bollywood-Unwind-Romantic-Classics-in-a-Relaxing-Urban-Avatar-Hindi-2015-500x500.jpg",
        "is_dolby_content": false,
        "label": "Strumm Entertainment",
        "label_url": "/label/strumm-entertainment-albums/MxcESb9iLFU_",
        "language": "hindi",
        "lyrics_snippet": "छू कर मेरे मन को किया तूने क्या इशारा?",
        "media_preview_url": "https://preview.saavncdn.com/001/f687c7d8c1001710b126fb4b46b64945_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/001/f687c7d8c1001710b126fb4b46b64945_320.mp4",
        "music": "Rajesh Roshan",
        "music_id": "455518",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/chhukar-mere-man-ko-unwind-version/SF8ufENJAX8",
        "play_count": 2681831,
        "primary_artists": "Mohammed Irfan, Rajesh Roshan",
        "primary_artists_id": "743983, 455518",
        "release_date": "2015-01-01",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Mohammed Irfan",
        "song": "Chhukar Mere Man Ko - Unwind Version",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010911100799002",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010911100755484.mp3",
        "webp": false,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Bollywood Unwind - Romantic Classics in a Relaxing Urban Avatar",
        "album_url": "https://www.jiosaavn.com/album/bollywood-unwind-romantic-classics-in-a-relaxing-urban-avatar/MCsq4ztvlRY_",
        "albumid": "1452346",
        "artistMap": {
            "Ash King": "459583",
            "Indeevar": "456004",
            "Kalyanji Anandji": "599595"
        },
        "cache_state": "false",
        "copyright_text": "©  2015 Strumm Entertainment",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "214",
        "encrypted_media_path": "NMKyboFo/FgL/hIM/OPzbnW1Dpd6IGvgivzX7zmykbOOMxFUry7h1sP30yHUT6om",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyEXiBsbAwpQ7+3oCNJS5N8ZKVAymBEH+NJ22xA5f94ItRtnkD6yiioRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "a1GICAtJ",
        "image": "https://c.saavncdn.com/001/Bollywood-Unwind-Romantic-Classics-in-a-Relaxing-Urban-Avatar-Hindi-2015-500x500.jpg",
        "is_dolby_content": false,
        "label": "Strumm Entertainment",
        "label_url": "/label/strumm-entertainment-albums/MxcESb9iLFU_",
        "language": "hindi",
        "lyrics_snippet": "Lyrics",
        "media_preview_url": "https://preview.saavncdn.com/001/c9210d7162c61dc688f4fb0cdb210460_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/001/c9210d7162c61dc688f4fb0cdb210460_320.mp4",
        "music": "Kalyanji Anandji",
        "music_id": "599595",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/neele-neele-ambar-par-unwind-version/EVkseDdxQ3k",
        "play_count": 2787548,
        "primary_artists": "Ash King, Kalyanji Anandji",
        "primary_artists_id": "459583, 599595",
        "release_date": "2015-01-01",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Ash King",
        "song": "Neele Neele Ambar Par - Unwind Version",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010911100798996",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010911100755478.mp3",
        "webp": false,
        "year": "2015"
    }
]

export const romanseSongs = [
    {
        "320kbps": "true",
        "album": "Maari",
        "album_url": "https://www.jiosaavn.com/album/maari/sdjpUZo9-HI_",
        "albumid": "1251943",
        "artistMap": {
            "Alisha Thomas": "852328",
            "Anirudh Ravichander": "455663",
            "Dhanush": "455662",
            "Kajal Aggarwal": "479962",
            "Vijay Yesudas": "455508"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2015 Sony Music Entertainment India Pvt. Ltd.",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "198",
        "encrypted_media_path": "NMKyboFo/FjfeSkxFSPJUsYtD6UY61S6l8o29Djc5L6pyxdq2GwY6LQdPiXVE/pY",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDymj8i23FAu9Rv/Xw82Gvq9OTyBAYGlIq7xcxCApLEb/mZCahnuDnmfBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "eUgNtCfF",
        "image": "https://c.saavncdn.com/098/Maari-Tamil-2015-20200806144615-500x500.jpg",
        "is_dolby_content": false,
        "label": "Sony Music Entertainment India Pvt. Ltd.",
        "label_url": "/label/sony-music-entertainment-india-pvt.-ltd.-albums/LaFAA6h1q2U_",
        "language": "tamil",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/098/b78c21845f8c057dde7375d09714da85_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/098/b78c21845f8c057dde7375d09714da85_320.mp4",
        "music": "Anirudh Ravichander",
        "music_id": "455663",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/donu-donu-donu-the-dons-romance/FT0MfwBzUXU",
        "play_count": 25380940,
        "primary_artists": "Anirudh Ravichander, Alisha Thomas",
        "primary_artists_id": "455663, 852328",
        "release_date": "2015-06-07",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Anirudh Ravichander, Alisha Thomas",
        "song": "Don'u Don'u Don'u (The Don's Romance)",
        "starred": "false",
        "starring": "Dhanush, Kajal Aggarwal, Vijay Yesudas",
        "triller_available": false,
        "type": "",
        "vcode": "010910140014009",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910140016787.mp3",
        "webp": true,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Romance Like SRK - Mashup",
        "album_url": "https://www.jiosaavn.com/album/romance-like-srk-mashup/9QAzzd4SXlk_",
        "albumid": "1224192",
        "artistMap": {
            "A.R. Rahman": "456269",
            "Anand Bakshi": "456000",
            "Gulzar": "455704",
            "Jaideep Sahni": "464645",
            "Javed Akhtar": "455447",
            "Lata Mangeshkar": "455109",
            "Madan Mohan": "455994",
            "Mohit Chauhan": "455124",
            "Roopkumar Rathod": "455459",
            "Salim-Sulaiman": "456102",
            "Shreya Ghoshal": "455130",
            "Sonu Nigam": "455125",
            "Sunny Subramanian": "615445",
            "Udit Narayan": "455127",
            "Uttam Singh": "461323"
        },
        "cache_state": "false",
        "copyright_text": "©  2015 YRF Music",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "206",
        "encrypted_media_path": "NMKyboFo/FifJvv2QnVM5zjL9lVsosxTSW7jgynTKFcFKs6y5jOu53Oz/l3Ws1wN",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyXYHVQGxLNeIzpUi5RmwWwS5sUFn96Gff71w0osXDvROTbKhZfUHv0Bw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "_ovxilTH",
        "image": "https://c.saavncdn.com/209/Romance-Like-SRK-Mashup-Hindi-2015-500x500.jpg",
        "is_dolby_content": false,
        "label": "YRF Music",
        "label_url": "/label/yrf-music-albums/XqFShgT4cps_",
        "language": "hindi",
        "lyrics_snippet": "main yahaan, hoon  yahaan, hoon  yahaan, hoon  yahaan",
        "media_preview_url": "https://preview.saavncdn.com/209/767f0d507529636a9711f612fb1d6ba3_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/209/767f0d507529636a9711f612fb1d6ba3_320.mp4",
        "music": "Salim-Sulaiman, Madan Mohan, A.R. Rahman, Uttam Singh",
        "music_id": "456102, 455994, 456269, 461323",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-like-srk-mashup/LwcdSR1cY3s",
        "play_count": 2446808,
        "primary_artists": "Sunny Subramanian, Roopkumar Rathod, Lata Mangeshkar, Sonu Nigam, Shreya Ghoshal, Mohit Chauhan, Udit Narayan",
        "primary_artists_id": "615445, 455459, 455109, 455125, 455130, 455124, 455127",
        "release_date": "2015-02-13",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Sunny Subramanian, Roopkumar Rathod, Lata Mangeshkar, Sonu Nigam, Shreya Ghoshal, Mohit Chauhan, Udit Narayan",
        "song": "Romance Like SRK - Mashup",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": false,
        "year": "2015"
    },
    {
        "320kbps": "true",
        "album": "Shuddh Desi Romance",
        "album_url": "https://www.jiosaavn.com/album/shuddh-desi-romance/iM48O83xLxk_",
        "albumid": "1142649",
        "artistMap": {
            "Benny Dayal": "456521",
            "Jaideep Sahni": "464645",
            "Parineeti Chopra": "473372",
            "Rishi Kapoor": "455081",
            "Sachin-Jigar": "461968",
            "Shalmali": "467027",
            "Sushant Singh Rajput": "2180329",
            "Vaani Kapoor": "673052"
        },
        "cache_state": "false",
        "copyright_text": "©  2013 Yash Raj Films",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "186",
        "encrypted_media_path": "NMKyboFo/FglVjPcNcvYPBhBlR5rkvjXOXAYcz3M2TMQz33vqCZRfT5E8qqovwkI",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDypqD+WumPaC4qJE6wAvXvMHE+Ls82WbkgdOuTdY70FELYVpfbWeuBoxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "g86S97py",
        "image": "https://c.saavncdn.com/152/Shuddh-Desi-Romance-Hindi-2013-20190329150640-500x500.jpg",
        "is_dolby_content": false,
        "label": "Yash Raj Films",
        "label_url": "/label/yash-raj-films-albums/A3Yzr-GkEGE_",
        "language": "hindi",
        "lyrics_snippet": "शुद्ध देसी, देसी-देसी romance (कमीने, हाए, रे)",
        "media_preview_url": "https://preview.saavncdn.com/152/1866eb5742fcb88375d0573e754d6992_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/152/1866eb5742fcb88375d0573e754d6992_320.mp4",
        "music": "Sachin-Jigar",
        "music_id": "461968",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/shuddh-desi-romance/F1BdYk0HR0o",
        "play_count": 3188035,
        "primary_artists": "Sachin-Jigar, Benny Dayal, Shalmali",
        "primary_artists_id": "461968, 456521, 467027",
        "release_date": "2013-07-23",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Benny Dayal, Shalmali",
        "song": "Shuddh Desi Romance",
        "starred": "false",
        "starring": "Sushant Singh Rajput, Parineeti Chopra, Vaani Kapoor, Rishi Kapoor",
        "triller_available": false,
        "type": "",
        "vcode": "010910391621687",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910391577526.mp3",
        "webp": true,
        "year": "2013"
    },
    {
        "320kbps": "true",
        "album": "Tholi Prema",
        "album_url": "https://www.jiosaavn.com/album/tholi-prema/KbDktRPOXbI_",
        "albumid": "1219030",
        "artistMap": {
            "Ali": "460923",
            "Bhuvana Chandra": "455678",
            "Deva": "455219",
            "Keerthi Reddy": "462761",
            "P. Unnikrishnan": "586086",
            "Pawan Kalyan": "461297",
            "Suresh Peters": "460765"
        },
        "cache_state": "false",
        "copyright_text": "©  1998 YBR Music Publishing Pvt Ltd",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "287",
        "encrypted_media_path": "NMKyboFo/FgyUf0Z1wTgdwGL6BaCv2yz90ugecLfNW61V4P7bSMlbFsu5qgmnC96",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyhsg51fV0GlDbFXeyUdikITULixAi/AfNXJw9U7j/3F6It2DJoSxxixw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "8z3ukHsL",
        "image": "https://c.saavncdn.com/498/Tholi-Prema-Telugu-1998-500x500.jpg",
        "is_dolby_content": false,
        "label": "YBR Music Publishing Pvt Ltd",
        "label_url": "/label/ybr-music-publishing-pvt-ltd-albums/8vIYXCFLeKY_",
        "language": "telugu",
        "lyrics_snippet": "Romance Lo Rhythms Kalagalipina",
        "media_preview_url": "https://preview.saavncdn.com/498/6110cf4fad5e1ca97b59993cdaa8e83c_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/498/6110cf4fad5e1ca97b59993cdaa8e83c_320.mp4",
        "music": "Deva",
        "music_id": "455219",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-rythms/SBJYRB94RH8",
        "play_count": 969767,
        "primary_artists": "Deva, Suresh Peters, P. Unnikrishnan",
        "primary_artists_id": "455219, 460765, 586086",
        "release_date": "1998-07-24",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Suresh Peters, P. Unnikrishnan",
        "song": "Romance Rythms",
        "starred": "false",
        "starring": "Pawan Kalyan, Keerthi Reddy, Ali",
        "triller_available": false,
        "type": "",
        "vcode": "010910090839368",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910090795820.mp3",
        "webp": false,
        "year": "1998"
    },
    {
        "320kbps": "true",
        "album": "Jaan Tere Naam",
        "album_url": "https://www.jiosaavn.com/album/jaan-tere-naam/UakrIFtuSYA_",
        "albumid": "43200392",
        "artistMap": {
            "Farheen": "733182",
            "Kumar Sanu": "455142",
            "Nadeem-Shravan": "456307",
            "Ronit Roy": "455319",
            "Surendra Saathi": "476826"
        },
        "cache_state": "false",
        "copyright_text": "© 1992 Tips Industries Ltd.",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "413",
        "encrypted_media_path": "NMKyboFo/FgIgQ6WJleYKdoS5qFP9V+bEg9bPTkdnbwPbmkf6uJzvr6R1FViaR0b",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy35RwF1LTxgguW7+bICN+REVFU9GhM+2RlQ0Bt4IdrROFl44p7o6Lbxw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "2AYT4UsD",
        "image": "https://c.saavncdn.com/172/Jaan-Tere-Naam-Hindi-1992-20230304140459-500x500.jpg",
        "is_dolby_content": false,
        "label": "Tips Industries Ltd.",
        "label_url": "/label/tips-industries-ltd.-albums/,1uKiglGzEk_",
        "language": "hindi",
        "lyrics_snippet": "Mana ki college main perna chaiye like na chaiye.",
        "media_preview_url": "https://preview.saavncdn.com/172/ff32ded6f5ccc4d8911b0ea570d0189a_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/172/ff32ded6f5ccc4d8911b0ea570d0189a_320.mp4",
        "music": "Kumar Sanu, Nadeem-Shravan",
        "music_id": "455142, 456307",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romance-period/QikyZUBlRHc",
        "play_count": 604431,
        "primary_artists": "Kumar Sanu",
        "primary_artists_id": "455142",
        "release_date": "1992-02-21",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "",
        "song": "Romance Period",
        "starred": "false",
        "starring": "Ronit Roy, Farheen",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "1992"
    }
]

export const lofiSongs = [
    {
        "320kbps": "true",
        "album": "Sajna-Lofi",
        "album_url": "https://www.jiosaavn.com/album/sajna-lofi/tHacN1TFLmY_",
        "albumid": "37096195",
        "artistMap": {
            "Arijit Singh": "459320",
            "Arindom": "1312196",
            "Prasen": "532403"
        },
        "cache_state": "false",
        "copyright_text": "© 2022 SVF Music",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "188",
        "encrypted_media_path": "NMKyboFo/Fhb5abO5bYeBc49jf1WnEIyAQhml7+odpHMaEtPktW0wKbDxLzeX2AR",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyNGzozTPJ/32/AdU7YZqdhsGQyEGOlPrDRGub+eVk2xho/P0pUzF0VRw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "k03tA-da",
        "image": "https://c.saavncdn.com/216/Sajna-Lofi-Bengali-2022-20220806060504-500x500.jpg",
        "is_dolby_content": false,
        "label": "Shree Venkatesh Films Pvt. Ltd.",
        "label_url": "/label/shree-venkatesh-films-pvt.-ltd.-albums/9ijex,8qafE_",
        "language": "bengali",
        "lyrics_snippet": "साजना, लागे ना अब अखियाँ तोरे बिन",
        "media_preview_url": "https://preview.saavncdn.com/216/12e6aa733fb9d1d4a5f11493fc65536b_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/216/12e6aa733fb9d1d4a5f11493fc65536b_320.mp4",
        "music": "Arindom",
        "music_id": "1312196",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/sajna-lofi/G1hYRTUdU1I",
        "play_count": 3198674,
        "primary_artists": "Arijit Singh",
        "primary_artists_id": "459320",
        "release_date": "2022-08-05",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Arijit Singh",
        "song": "Sajna-Lofi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910091647423",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091603746.mp3",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Romantic Lofi (Slowed & Reverb)",
        "album_url": "https://www.jiosaavn.com/album/romantic-lofi-slowed-reverb/5tQeeUFO-JU_",
        "albumid": "39090781",
        "artistMap": {
            "Manish Zay": "14353980"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2022 Manish Zay Music",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "512",
        "encrypted_media_path": "NMKyboFo/Fix8b2IoZ2TMV6vra5eyQxohMO/92U+ZRzylnaog1CvvBxcszeoGszd",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDysgjPjHvqOCo3iv0MiHEWBQF1UpUi7pebPGGCWDZ8qjYYXtwzbK2q/hw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "0QnKJx4e",
        "image": "https://c.saavncdn.com/172/Romantic-Lofi-Slowed-Reverb-Hindi-2022-20221014234716-500x500.jpg",
        "is_dolby_content": false,
        "label": "Manish Zay Music",
        "label_url": "/label/manish-zay-music-albums/FeFiyK9ve30_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/172/330905dfa73d338765aa5f47c494c406_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/172/330905dfa73d338765aa5f47c494c406_320.mp4",
        "music": "Manish Zay",
        "music_id": "14353980",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/romantic-lofi-slowed-reverb/QDkFej5IA1Y",
        "play_count": 822520,
        "primary_artists": "Manish Zay",
        "primary_artists_id": "14353980",
        "release_date": "2022-10-14",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "",
        "song": "Romantic Lofi (Slowed & Reverb)",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2022"
    },
    {
        "320kbps": "true",
        "album": "Lo[ve]fi",
        "album_url": "https://www.jiosaavn.com/album/lovefi/E7J5s-CmGBQ_",
        "albumid": "28458987",
        "artistMap": {
            "Akshita": "1250784",
            "Akshita Singh": "11025734",
            "Luz Vandyke": "11025733",
            "Mary Herrington": "11025732"
        },
        "cache_state": "false",
        "copyright_text": "© 2021 Akshita",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "236",
        "encrypted_media_path": "NMKyboFo/FhwDgYCvfv26+YxqxRgIRP4+MU0wCA4AVCsO+pLa5F8WK/AaUU1nY+S",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyIYCOf52D25Ew+2XgFZk0v9hvDtilRQ5kw7/4jWgmAbrpiLTSRMsYPBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "5GZeEWwU",
        "image": "https://c.saavncdn.com/478/Lo-ve-fi-Hindi-2021-20210716010150-500x500.jpg",
        "is_dolby_content": false,
        "label": "Akshita",
        "label_url": "/label/akshita-albums/BC329HSQHvM_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/478/7d2175551e7512f7f63bf6b967428161_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/478/7d2175551e7512f7f63bf6b967428161_320.mp4",
        "music": "Akshita Singh",
        "music_id": "11025734",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/lovefi/RS8xVDFnQGY",
        "play_count": 62733,
        "primary_artists": "Akshita",
        "primary_artists_id": "1250784",
        "release_date": "2021-01-01",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Akshita",
        "song": "Lo[ve]fi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2021"
    },
    {
        "320kbps": "true",
        "album": "Tum Mile (Lofi Flip)",
        "album_url": "https://www.jiosaavn.com/album/tum-mile-lofi-flip/jpcTg9egglw_",
        "albumid": "28749361",
        "artistMap": {
            "KSW": "5119226",
            "Kumaar": "455665",
            "Neeraj Shridhar": "455694",
            "Neeraj Shridhar &amp; Pritam": "",
            "Pritam": "456323"
        },
        "cache_state": "false",
        "copyright_text": "(P) 2021 Sony Music Entertainment India Pvt. Ltd.",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "242",
        "encrypted_media_path": "NMKyboFo/FgbjqbTa4jG41SxvH6mA1E2dDWQ6+mJQk5WBDfj+tAbBCU+Fc+YcDqT",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDycTrDC9yCtwqX597IFy6j1Z8pGLRLjbwksuXf9LI01wm81URfLbqTcBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "false",
        "id": "iGsrkt9W",
        "image": "https://c.saavncdn.com/259/Tum-Mile-Lofi-Flip--Hindi-2021-20210730210034-500x500.jpg",
        "is_dolby_content": false,
        "label": "Sony Music Entertainment India Pvt. Ltd.",
        "label_url": "/label/sony-music-entertainment-india-pvt.-ltd.-albums/LaFAA6h1q2U_",
        "language": "hindi",
        "lyrics_snippet": "",
        "media_preview_url": "https://preview.saavncdn.com/259/1ee450f9addeccd7bb00e8ab19d9d3f4_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/259/1ee450f9addeccd7bb00e8ab19d9d3f4_320.mp4",
        "music": "Pritam",
        "music_id": "456323",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/tum-mile-lofi-flip/GS8YQx9EDmQ",
        "play_count": 12032482,
        "primary_artists": "KSW, Neeraj Shridhar, Pritam",
        "primary_artists_id": "5119226, 455694, 456323",
        "release_date": "2021-08-13",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "KSW, Neeraj Shridhar, Pritam, KSW, Neeraj Shridhar & Pritam",
        "song": "Tum Mile (Lofi Flip)",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "vcode": "010910141422379",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910141378295.mp3",
        "webp": true,
        "year": "2021"
    },
    {
        "320kbps": "true",
        "album": "Naah Lofi",
        "album_url": "https://www.jiosaavn.com/album/naah-lofi/SfeCbpBK7GA_",
        "albumid": "35360265",
        "artistMap": {
            "Jass Manak": "4698047"
        },
        "cache_state": "false",
        "copyright_text": "© 2022 Geet MP3",
        "disabled": "true",
        "disabled_text": "Pro Only",
        "duration": "198",
        "encrypted_media_path": "NMKyboFo/FjvmkdVC9S/tzemtGPJlbXyIeEfd0qjWMnCDPm4NvmUO7U1Avm5Z7Qo",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyXeWduFYW60uTdbktYH4waDQUAGKNbsqnppudkfd/koZ+4Ueqkx2yFBw7tS9a8Gtq",
        "explicit_content": 0,
        "featured_artists": "",
        "featured_artists_id": "",
        "has_lyrics": "true",
        "id": "p0pe2It5",
        "image": "https://c.saavncdn.com/809/Naah-Lofi-Hindi-2022-20220803210006-500x500.jpg",
        "is_dolby_content": false,
        "label": "GK. Digital",
        "label_url": "/label/gk.-digital-albums/aguA5abrFcA_",
        "language": "punjabi",
        "lyrics_snippet": "nahiyon hona mainu tere naa' pyaar ve",
        "media_preview_url": "https://preview.saavncdn.com/809/566ada21bfe119742209581bf7aaa8f3_96_p.mp4",
        "media_url": "https://aac.saavncdn.com/809/566ada21bfe119742209581bf7aaa8f3_320.mp4",
        "music": "",
        "music_id": "",
        "origin": "none",
        "perma_url": "https://www.jiosaavn.com/song/naah-lofi/AFgbVEZ5QwY",
        "play_count": 2401658,
        "primary_artists": "Jass Manak",
        "primary_artists_id": "4698047",
        "release_date": "2022-05-30",
        "rights": {
            "cacheable": true,
            "code": 1,
            "delete_cached_object": false,
            "reason": "Pro Only"
        },
        "singers": "Jass Manak",
        "song": "Naah Lofi",
        "starred": "false",
        "starring": "",
        "triller_available": false,
        "type": "",
        "webp": true,
        "year": "2022"
    }
]